// <auto-generated />
using System;
using Ildiko_Antal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ildiko_Antal.Migrations
{
    [DbContext(typeof(Ildiko_AntalContext))]
    [Migration("20220217105727_InnitialMigrate")]
    partial class InnitialMigrate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ildiko_Antal.Models.Adapost", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("adresaadapost")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("denumireadapost")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("ID");

                    b.ToTable("Adapost");
                });

            modelBuilder.Entity("Ildiko_Antal.Models.Animale", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdapostID");

                    b.Property<int>("SpecieID");

                    b.Property<string>("altedetalii")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<DateTime>("checkin");

                    b.Property<string>("nume")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("regim")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("ID");

                    b.HasIndex("AdapostID");

                    b.HasIndex("SpecieID");

                    b.ToTable("Animale");
                });

            modelBuilder.Entity("Ildiko_Antal.Models.Specie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("denumirespecie")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("ID");

                    b.ToTable("Specie");
                });

            modelBuilder.Entity("Ildiko_Antal.Models.Animale", b =>
                {
                    b.HasOne("Ildiko_Antal.Models.Adapost", "Adapost")
                        .WithMany()
                        .HasForeignKey("AdapostID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ildiko_Antal.Models.Specie", "Specie")
                        .WithMany()
                        .HasForeignKey("SpecieID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
